### ISSUE TITLE
Install directory inconsistency

### ISSUE THREAD

**Issue by patflick** [ROCmSoftwarePlatform/hipBLAS#14]
This is not really a bug, but it seems kind of inconsistent. The hipblas .deb package is installed into `/usr/include` and `/usr/lib`, whereas most other `rocm` packages install into `/opt/rocm`.

**Comment by amcamd** [comment]
Thank you for reporting this inconsistency. The new release hipBLAS-0.4.3.0 installs in /opt/rocm.

**Comment by kknox** [comment]
This has been fixed for a while, probably starting in our v0.6 release.
