### ISSUE TITLE
Disrespecting CMake option `BUILD_WITH_SOLVER`

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCmSoftwarePlatform/hipBLAS#195]
### What is the expected behavior
- Guarding rocSOLVER specific code paths based on CMake option

### What actually happens
- Unconditional `#include "rocsolver.h"` in `hipblas.cpp` resulting in failing build.

### How to reproduce
- Default specifying `-D BUILD_WITH_SOLVER=OFF`

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v3.3-19 |
| ROCR | v3.3-19 |
| HCC | v3.1.20114-6776c83f-1 |
| Library | master @ [29b3fb0](https://github.com/ROCmSoftwarePlatform/hipBLAS/commit/29b3fb0aa15da8bc8050a9298716c908b515bfd1) |

**Comment by leekillough** [comment]
See #193
