### ISSUE TITLE
Error : There is no device can be used to do the computation for HIP_PLATFORM NVCC

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/hipBLAS#48]
**Background**
“Error: There is no device can be used to do the computation”, while executing MXNet tests on HIP/CUDA (NVCC) path after integrating hipBLAS

**Issue**
Facing runtime issues on integrating hipBLAS to MXNet library . “error: There is no device can be used to do the computation”. (Test cases terminate after throwing this error)
Attached sample application which will reproduce the above mentioned error 
[hipblas_test.cpp.zip](https://github.com/ROCmSoftwarePlatform/hipBLAS/files/1664006/hipblas_test.cpp.zip)

**Steps to reproduce**
- $git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet 
- $cd mxnet
- $export HIP_PLATFORM=nvcc
- $make -j(nproc)
- $unzip hipblas_test.cpp.zip
- $cp hipblas_test.cpp mxnet/
- $/opt/rocm/bin/hipcc -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 hipblas_test.cpp -I../ -I/usr/local/cuda-8.0/include -I/opt/rocm/hipblas/include -L/opt/rocm/hipblas/lib  -lhipblas -lcublas -o hipblas_test.cpp.out
- $./hipblas_test.cpp.out

**Analysis**
Though the error indicates absence of device, the gpu is being detected. The image of nvidia-smi log has been attached.
![nvdia-smi log](https://user-images.githubusercontent.com/25496668/35389110-6d681a3c-01fc-11e8-897d-eee8aadfe527.png)

**Comment by gstoner** [comment]
You should not use rocBLAS on NVIDIA use cuBLAS
