### ISSUE TITLE
hipConfig.cmake issue on NVIDIA

### ISSUE THREAD

**Issue by Prasandhmcw** [ROCmSoftwarePlatform/hipBLAS#53]
While installing on NVIDIA, hipBLAS searches for hipConfig.cmake but hipConfig.cmake will be generated only on HCC Platform while installing HIP.

**Comment by NEELMCW** [comment]
@amcamd  #54  should fix this. Let me know if there are any issues

**Comment by Kaveh01** [comment]
@amcamd this is fixed on @NEELMCW fork but not merged yet.

**Comment by sriharikarnam** [comment]
@amcamd 

While building  on NVIDIA, hipBLAS searches for CUDA_cublas_device_LIBRARY path and fails on ubuntu 18.04 with cuda-10.1

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168


-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "hipblas" in directory /home/cuda/Workspace/libraries/hipBLAS/library/src

-- Configuring incomplete, errors occurred!
See also "/home/cuda/Workspace/libraries/hipBLAS/build/CMakeFiles/CMakeOutput.log".
See also "/home/cuda/Workspace/libraries/hipBLAS/build/CMakeFiles/CMakeError.log".

**Comment by CadeBrown** [comment]
I also have this problem. @NEELMCW 's branch fixes the issue with hipBLAS trying to select hcc backend all the time, it still gives the error

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "hipblas" in directory /home/cade/hipBLAS_FIX/library/src

```


However, I found out the problem, it is a CMake versioning problem. I was using CMake 3.10, and I switch to 3.12.4, and the problem went away. It now compiles hipBLAS correctly

**Comment by tcojean** [comment]
I am also encountering the problems reported here. The alternatives are either to install all `hip_hcc` stack, although that is unneeded with a `nvcc` backend (and heavy for containers), or using @NEELMCW's fork.
