### ISSUE TITLE
hipblasSgemm extremely slow when compared to cublasSgemm

### ISSUE THREAD

**Issue by jordan44665** [ROCmSoftwarePlatform/hipBLAS#582]
### What is the expected behavior
Would expect the performance of GEMM operations to be comparable to cublas GEMM operations.

### What actually happens
The GEMM operations on floats is extremely slow.

### How to reproduce
See attached test case. Compile test case with -D CUDA and run on an NVIDIA GPU and recompile with -D HIP and run on an AMD Hipyfied AMD GPU and compare the results.

### Environment
| Hardware | description |
A Linux desktop with Radeon PRO W6800 and a Linux desktop with GeForce RTX 2060 SUPER.
| GPU | device string |
19:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 GL-XL [Radeon PRO W6800]
| CPU | device string |

| Software | version |
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"

| ROCK | v0.0 |
Runtime Version:         1.1
| ROCR | v0.0 |
| HCC | v0.0 |
HIP version: 5.2.21153-02187ecf
| Library | v0.0 |

I ran it on my two desktops -- one with Radeon W6800 and the other with GeForce RTX 2060. See attached GemmTest.cpp and here are the results:

GeForce RTX 2060:

size 512 average 8.85824e-05 s 
size 1024 average 0.000308755 s 
size 2048 average 0.00214913 s 
size 4096 average 0.0187068 s 
size 8192 average 0.153399 s 
size 16384 average 1.2847 s 

Radeon W6800:

size 512 average 0.262805 s 
size 1024 average 0.0126241 s 
size 2048 average 0.118601 s 
size 4096 average 0.794954 s 
size 8192 average 3.916 s 
size 16384 average 26.0589 s 

```
#include <unistd.h>
#include <iostream>
#include <stdlib.h>
#include <assert.h>

#if defined(CUDA)
#include <cuda_runtime.h>
#include <cublas_v2.h>

#define GPUBLAS_OP_N CUBLAS_OP_N

typedef cudaError_t gpuError_t;
typedef cudaEvent_t gpuEvent_t;
typedef cudaStream_t gpuStream_t;

typedef cublasHandle_t gpuBlasHandle_t;
typedef cublasStatus_t gpuBlasStatus_t;

const gpuBlasStatus_t gpuBlasSuccess = CUBLAS_STATUS_SUCCESS;

const gpuError_t gpuSuccess = cudaSuccess;

#define gpuMemcpyHostToDevice cudaMemcpyHostToDevice

gpuError_t gpuMemcpy(void* dest, void* src, size_t size, cudaMemcpyKind flags) {
  return cudaMemcpy(dest, src, size, flags);
}

gpuError_t gpuMallocManaged(void** ret, size_t size) {
  return cudaMallocManaged(ret, size);
}

gpuError_t gpuEventCreate(gpuEvent_t* pevent) {
  return cudaEventCreate(pevent);
}

gpuError_t gpuEventRecord(gpuEvent_t event, gpuStream_t stream) {
  return cudaEventRecord(event, stream);
}

gpuError_t gpuEventSynchronize(gpuEvent_t event) {
  return cudaEventSynchronize(event);
}

gpuError_t gpuGetLastError() {
  return cudaGetLastError();
}

gpuError_t gpuEventElapsedTime(float* t, gpuEvent_t start, gpuEvent_t stop) {
  return cudaEventElapsedTime(t, start, stop);
}

gpuError_t gpuFree(void* p) {
  return cudaFree(p);
}

gpuBlasStatus_t gpuBlasCreate(gpuBlasHandle_t* phandle) {
  return cublasCreate(phandle);
}

gpuBlasStatus_t gpuBlasSgemm(gpuBlasHandle_t handle, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k, const float* alpha, const float* a, int lda, const float* b, int ldb, const float* beta, float* c, int ldc) {
  return cublasSgemm(handle, ta, tb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc);
}

#elif defined(HIP)
#include <hip/hip_runtime.h>
#include <hip/hip_runtime_api.h>
#include <hipblas/hipblas.h>
#include <hiprand/hiprand.h>

#define GPUBLAS_OP_N HIPBLAS_OP_N

typedef hipError_t gpuError_t;
typedef hipEvent_t gpuEvent_t;
typedef hipStream_t gpuStream_t;

typedef hipblasHandle_t gpuBlasHandle_t;
typedef hipblasStatus_t gpuBlasStatus_t;

const gpuBlasStatus_t gpuBlasSuccess = HIPBLAS_STATUS_SUCCESS;

const gpuError_t gpuSuccess = hipSuccess;

#define gpuMemcpyHostToDevice hipMemcpyHostToDevice

gpuError_t gpuMemcpy(void* dest, void* src, size_t size, hipMemcpyKind flags) {
  return hipMemcpy(dest, src, size, flags);
}

gpuError_t gpuMallocManaged(void** ret, size_t size) {
  return hipMallocManaged(ret, size);
}

gpuError_t gpuEventCreate(gpuEvent_t* pevent) {
  return hipEventCreate(pevent);
}

gpuError_t gpuEventRecord(gpuEvent_t event, hipStream_t stream) {
  return hipEventRecord(event, stream);
}

gpuError_t gpuEventSynchronize(gpuEvent_t event) {
  return hipEventSynchronize(event);
}

gpuError_t gpuGetLastError() {
  return hipGetLastError();
}

gpuError_t gpuEventElapsedTime(float* t, gpuEvent_t start, gpuEvent_t stop) {
  return hipEventElapsedTime(t, start, stop);
}

gpuError_t gpuFree(void* p) {
  return hipFree(p);
}

gpuBlasStatus_t gpuBlasCreate(gpuBlasHandle_t* phandle) {
  return hipblasCreate(phandle);
}

gpuBlasStatus_t gpuBlasSgemm(gpuBlasHandle_t handle, hipblasOperation_t ta, hipblasOperation_t tb, int m, int n, int k, const float* alpha, const float* a, int lda, const float* b, int ldb, const float* beta, float* c, int ldc) {
  return hipblasSgemm(handle, ta, tb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc);
}

#else
#error "Specify GPU type"
#endif


void initRand(float* p, int rows, int cols) {
  int a = 1;

  for (int i = 0; i < rows * cols; i++) {
    p[i] = (float) rand() / (float) (RAND_MAX / a);
  }
}

int main(int argc, char* argv[]) {
  int status, lower, upper, num, reps, verbose;

  lower = 256;
  upper = 8192;
  num = 25000;
  reps = 5;
  verbose = 0;

  while ((status = getopt(argc, argv, "l:u:n:r:v")) != -1) {
    switch (status) {
    case 'l':
      lower = strtoul(optarg, 0, 0);
      break;
    case 'u':
      upper = strtoul(optarg, 0, 0);
      break;
    case 'n':
      num = strtoul(optarg, 0, 0);
      break;
    case 'r':
      reps = strtoul(optarg, 0, 0);
      break;
    case 'v':
      verbose = strtoul(optarg, 0, 0);
      break;
    default:
      std::cerr << "invalid argument: " << status << std::endl;
      exit(1);
    }
  }

  if (verbose) {
    std::cout << "Running with" << " lower: " << lower << " upper: " << upper << " num: " << num << " reps: " << reps << std::endl;
  }

  if (verbose) {
    std::cout << "initializing inputs" << std::endl;
  }

  gpuBlasHandle_t handle;
  gpuBlasStatus_t blasStatus;

  blasStatus = gpuBlasCreate(&handle);
  if (blasStatus != gpuBlasSuccess) {
    std::cerr << "Could not create blas handle " << blasStatus << std::endl;
    exit(1);
  }

  float* A = (float*) calloc(1, upper * upper * sizeof(float));
  float* B = (float*) calloc(1, upper * upper * sizeof(float));
  float* C = (float*) calloc(1, upper * upper * sizeof(float));

  initRand(A, upper, upper);
  initRand(B, upper, upper);
  initRand(C, upper, upper);

  float* dA, *dB, *dC;
  gpuError_t err;

  int lda, ldb, ldc, m, n, k;
  float alpha = 1.0f, beta = 0.0f;

  err = gpuMallocManaged((void**) &dA, upper * upper * sizeof(float));
  if (err != gpuSuccess) {
    std::cerr << "Could not allocate GPU memory; size: " << upper * upper * sizeof(float) << std::endl;
  }

  err = gpuMallocManaged((void**) &dB, upper * upper * sizeof(float));
  if (err != gpuSuccess) {
    std::cerr << "Could not allocate GPU memory; size: " <<  upper * upper * sizeof(float) << std::endl;
  }

  err = gpuMallocManaged((void**) &dC, upper * upper * sizeof(float));
  if (err != gpuSuccess) {
    std::cerr << "Could not allocate GPU memory; size: " << upper * upper * sizeof(float) << std::endl;
  }

  err = gpuMemcpy(dA, A, upper * upper * sizeof(float), gpuMemcpyHostToDevice);
  if (err != gpuSuccess) {
    std::cerr << "Could not copy to GPU memory; size: " << upper * upper * sizeof(float) << std::endl;
  }

  err = gpuMemcpy(dB, B, upper * upper * sizeof(float), gpuMemcpyHostToDevice);
  if (err != gpuSuccess) {
    std::cerr << "Could not copy to GPU memory; size: " << upper * upper * sizeof(float) << std::endl;
  }

  err = gpuMemcpy(dC, C, upper * upper * sizeof(float), gpuMemcpyHostToDevice);
  if (err != gpuSuccess) {
    std::cerr << "Could not copy to GPU memory; size: " << upper * upper * sizeof(float) << std::endl;
  }
  gpuEvent_t start, stop;
  gpuEventCreate(&start);
  gpuEventCreate(&stop);

  for (int s = lower; s <= upper; s = s * 2) {
    double sum = 0.0;
    for (int r = 0; r < reps; r++) {
      gpuEventRecord(start, 0);
      m = n = k = s;
      lda = m; ldb = k; ldc = m;

      blasStatus = gpuBlasSgemm(handle, GPUBLAS_OP_N, GPUBLAS_OP_N, m, n, k, &alpha, dA, lda, dB, ldb, &beta, dC, ldc);
      gpuEventRecord(stop, 0);
      gpuEventSynchronize(stop);
      if (blasStatus != gpuBlasSuccess) {
        std::cerr << "gpuBlasSgemm failed: " << blasStatus << std::endl;
        exit(1);
      }
      err = gpuGetLastError();
      if (err != gpuSuccess) {
        std::cerr << "gpu error: " << err << std::endl;
        exit(1);
      }

      float elapsed;
      gpuEventElapsedTime(&elapsed, start, stop);
      elapsed /= 1000.0f;
      sum += elapsed;
    }
    std::cout << "size " << s << " average " << sum / reps << " s " << std::endl;
  }

  gpuFree(dA); gpuFree(dB); gpuFree(dC);
  free(A); free(B); free(C);
}
```

**Comment by daineAMD** [comment]
Hi @jordan44665, thanks for opening this issue.

I see that you're using `hipMallocManaged()` to allocate your device memory. [The HIP managed memory documentation](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_programming_guide.md#managed-memory-allocation) recommends calling `hipDeviceGetAttribute()` to query `hipDeviceAttributeManagedMemory` before allocating memory using `hipMallocManaged()`. Can you please try this to see if it is supported on your device? I think this is the root of your performance woes.

If it is not supported, can you try changing `hipMallocManaged` to `hipMalloc` in your code? I hope this will make the performance more in line with what you're expecting.

Also note that there is a one-time startup cost to load gemm kernels for the first call to hipblasSgemm, as seen with your 512 case being slower than your 1024 case. When measuring performance you can try adding "cold call(s)" outside of the timing framework to avoid measuring this one-time cost.

Thanks,
Daine

**Comment by jordan44665** [comment]
Hi @daineAMD,

I changed the hipMallocManaged() to hipMalloc (see attached source). The numbers for the W6800 are mostly better than before but still significantly higher than expected. And here are the results:

---------------- W6800 -----------------
size 256 average 0.256122 s 
size 512 average 0.000284425 s 
size 1024 average 0.000909363 s 
size 2048 average 0.00233341 s 
size 4096 average 0.0078005 s 
size 8192 average 0.071839 s 

---------- RTX 2060 ---------
size 256 average 5.9744e-05 s 
size 512 average 6.02688e-05 s 
size 1024 average 0.000408064 s 
size 2048 average 0.00289365 s 
size 4096 average 0.0236227 s 
size 8192 average 0.156054 s 

-------------------------------
I just changed the following functions:

gpuMallocManaged() to gpuMalloc() in main() -- three instances

cudaMallocManaged() to cudaMalloc()
hipMallocManaged() to hipMalloc()

If you like, I can attach the full source with the modifications.

**Comment by daineAMD** [comment]
Hi again,

These numbers look fairly reasonable to me, at least for the large sizes. Those times correspond to ~17.6 Tflops for size = 4096 and ~15.3 Tflops for size = 8192 which seems fairly close to peak performance on this hardware.

The smaller sizes likely haven't gotten as much focus for tuning on navi21. With AMD backend, we use Tensile for gemm kernels; you can try opening an issue at the [Tensile repo](https://github.com/rocmsoftwareplatform/tensile) and specify specific sizes you're interested in for tuning and see if they can help. hipBLAS is just a wrapper to rocBLAS/cuBLAS backends, so it doesn't really have any major impact on performance.

As for the size=256 performance, it's still getting the startup initialization cost, it would be more accurate to do a "warm up" call to hipblasSgemm() before benchmarking the call.

Thanks again,
Daine

**Comment by daineAMD** [comment]
@jordan44665 I'll close this issue as I haven't heard back in a while and I think the crux of the issue is resolved. Hopefully Tensile folks can help you out if you have tuning requests for any specific sizes. Feel free to re-open if I haven't addressed any of your concerns, thanks!
