### ISSUE TITLE
Building rocBLAS for CUDA backend fails

### ISSUE THREAD

**Issue by torrance** [ROCmSoftwarePlatform/hipBLAS#603]
I'm building using CMake directly[1] for CUDA backend:

```
# On branch release/rocm-rel-5.5
mkdir build && cd build
cmake -DUSE_CUDA=ON -DHIP_ROOT_DIR=/opt/rocm ..
make

Scanning dependencies of target hipblas_fortran
[ 20%] Building Fortran object library/src/CMakeFiles/hipblas_fortran.dir/hipblas_module.f90.o
[ 40%] Linking Fortran shared library libhipblas_fortran.so
[ 40%] Built target hipblas_fortran
[ 60%] Building CXX object library/src/CMakeFiles/hipblas.dir/nvidia_detail/hipblas.cpp.o
In file included from /home/torrance/hipBLAS/library/src/nvidia_detail/hipblas.cpp:27:
/usr/local/cuda/include/cublas_v2.h:59:2: error: #error "It is an error to include both cublas.h and cublas_v2.h"
   59 | #error "It is an error to include both cublas.h and cublas_v2.h"
      |  ^~~~~
```

I can compile with the following changes, though I don't know if this is properly functional or not:

```diff
diff --git a/library/src/nvidia_detail/hipblas.cpp b/library/src/nvidia_detail/hipblas.cpp
index b60a31d..08a6257 100644
--- a/library/src/nvidia_detail/hipblas.cpp
+++ b/library/src/nvidia_detail/hipblas.cpp
@@ -23,7 +23,7 @@

 #include "hipblas.h"
 #include "exceptions.hpp"
-#include <cublas.h>
+//#include <cublas.h>
 #include <cublas_v2.h>
 #include <cuda_runtime_api.h>
 #include <hip/hip_runtime.h>
@@ -350,7 +350,7 @@ hipblasStatus_t hipblasGetPointerMode(hipblasHandle_t handle, hipblasPointerMode
 try
 {
     cublasPointerMode_t cublasMode;
-    cublasStatus        status = cublasGetPointerMode((cublasHandle_t)handle, &cublasMode);
+    cublasStatus_t        status = cublasGetPointerMode((cublasHandle_t)handle, &cublasMode);
     *mode                      = CudaPointerModeToHIPPointerMode(cublasMode);
     return hipCUBLASStatusToHIPStatus(status);
 }
```

[1] i.e. not using the install.sh script, though the error is present in both obviously. Honestly though, why this install script, when the rest of the hip ecosystem uses CMake? And why default to making a .deb package?

### Environment
| Hardware | description |
|-----|-----|
| GPU | Tesla T4 |
| CPU | Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz |

| Software | version |
|-----|-----|
| HIP | v5.5 |
| CUDA | 12.1 |

**Comment by daineAMD** [comment]
Hi @torrance,

I've added the fixes in develop at [55dc014a](https://github.com/ROCmSoftwarePlatform/hipBLAS/commit/55dc014a4eb36b4fdf97a5dfefa325b8e43ae058) and as a hot-fix into ROCm 5.7 at [aadde8ae](https://github.com/ROCmSoftwarePlatform/hipBLAS/commit/aadde8ae50817559bd69d13cc49083cfdf9441d4).

Thanks again for bringing this up and having a fix ready! I'll close the ticket now.

Daine
