### ISSUE TITLE
64-bit interface

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipBLAS#691]
Does the BLAS (e.g. hipblasIdamax) function support 64-bit interface ? Thanks.

https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-0/iamax.html

**Comment by TorreZuk** [comment]
Currently hipBLAS and rocBLAS do not support the 64-bit integer interfaces.  The Level 1 functions including iamax iamin with 64-bit integer form are a planned addition so should be available in a future release.  We can post here when they arrive.

**Comment by jinz2014** [comment]
Thanks for your update when they arrive.

**Comment by TorreZuk** [comment]
rocBLAS has ILP64 interfaces for Level 1 BLAS added in develop branch for future release, so work on adding these to hipBLAS can begin soon.

**Comment by daineAMD** [comment]
HI @jinz2014,

ILP64 interfaces for all L1 and L2 functions are supported in hipBLAS as of [ROCm 6.2](https://rocm.docs.amd.com/en/docs-6.2.0/). Most L1 functions were added in 6.1.0, and the remaining ILP64 interfaces should land in the next ROCm release.

I'll close this issue now, feel free to re-open if needed.

Thanks,
Daine
