### ISSUE TITLE
question about axpby 

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipBLAS#747]
Would "axpby" (https://oneapi-src.github.io/oneMKL/domains/blas/axpby.html) be added to hip/roc-BLAS ?

**Comment by mahmoodw** [comment]
Hi @jinz2014 ,

Thank you for reaching out and suggesting this addition! Your input is greatly appreciated. I'll make sure to bring this up with the team to discuss the commonality of its usage and feasibility for implementation.

We value your feedback in enhancing our libraries and will keep you updated on any developments regarding this suggestion.

Best regards,
Wasiq

**Comment by jinz2014** [comment]
@mahmoodw   Thank you for the comments and discussion.

**Comment by amcamd** [comment]
Hello @jinz2014. We do not have a compelling enough use case to add axpby. We could reconsider adding axpby and reopen this issue if we knew of a use case. It can also be noted that hipBLAS is a compatibility layer for rocBLAS and cuBLAS. axpby is not part of cuBLAS, so if it was added it would be more appropriate to add it to rocBLAS.
