### ISSUE TITLE
hipblasXgelsBatched() failed with error

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipBLAS#857]
Running the HIP program produces some error. I migrated the program from CUDA to HIP. Thanks.

To reproduce:
```
go to https://github.com/zjin-lcf/HeCBench/tree/master/src/gels-hip
type 'make'
type './main 1'
```
ERROR: hipblasXgelsBatched() failed with error HIPBLAS_STATUS_INVALID_VALUE..

**Comment by daineAMD** [comment]
Hi @jinz2014,

I made a few changes to your test, and it seems to be working now. NULL was being passed into `hipblasSgelsBatched()` for the `deviceInfo` param, causing the HIPBLAS_STATUS_INVALID_VALUE result. In the future, you can read the `info` param for some of these solver functions to get a hint at invalid return values.

You can see my changes at https://github.com/daineAMD/HeCBench/commit/f64819a20b52a6bad071d3f5c237c842248bf76f.

Also, you can browse the `hipblasSgelsBatched()` docs and the `deviceInfo` param [in the hipBLAS docs](https://rocm.docs.amd.com/projects/hipBLAS/en/latest/functions.html#_CPPv419hipblasZgelsBatched15hipblasHandle_t18hipblasOperation_tKiKiKiA_PC20hipblasDoubleComplexKiA_PC20hipblasDoubleComplexKiPiPiKi).

Let me know if you have any further questions or issues. Thanks,
Daine
