### ISSUE TITLE
Results of hipblasHgemm seems incorrect

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipBLAS#861]
I tried to run an example that calls the hipblasHgemm function on a gfx908 GPU. The results seemed incorrect when comparing the results of the half- and single-precision versions. Thanks.

https://github.com/zjin-lcf/HeCBench/tree/master/src/mkl-sgemm-hip 

```
HIP version: 6.0.32831-204d35d16
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.2 24012 af27734ed982b52a9f1be0f035ac91726fc697e4)

hipcc  -std=c++17 -Wall -O3 gemm.o -o main -lhipblas
./main 79 91 83 1000
        Running with half precision real data type:
Average GEMM execution time: 542.991028 (us)

                Outputting 2x2 block of A,B,C matrices:

                        A = [ 0, 1, ...
                            [ 1, 1, ...
                            [ ...


                        B = [ 1, 0, ...
                            [ 1, 1, ...
                            [ ...


                        C = [ 0, 0, ...
                            [ 0, 0, ...
                            [ ...

        Running with single precision real data type:
Average GEMM execution time: 288.084442 (us)

                Outputting 2x2 block of A,B,C matrices:

                        A = [ 0, 1, ...
                            [ 1, 1, ...
                            [ ...


                        B = [ 1, 0, ...
                            [ 1, 1, ...
                            [ ...


                        C = [ 92, 96, ...
                            [ 116, 112, ...
                            [ ...

```

**Comment by daineAMD** [comment]
Hi @jinz2014,
`hipblasHalf` is just a typedef of `uint16_t` (unless HIPBLAS_USE_HIP_HALF is defined, in which case it uses HIP's `__half` type), so it isn't converting from/to floats as it seems you're expecting in your code. I've made some quick changes to your code at https://github.com/daineAMD/HeCBench/blob/hgemm/src/mkl-sgemm-hip/gemm.cu, they were just some quick changes to get it working so you may want to alter it a bit. It seems to be working now with both the uint16_t typedef and HIP __half. Can add `-mf16c` to compilation to get intrinsics, or add `-DHIPBLAS_USE_HIP_HALF` to use the HIP `__half` datatype within hipBLAS.

Let me know if you have any further questions,
Daine

**Comment by jinz2014** [comment]
I just added `-DHIPBLAS_USE_HIP_HALF` in Makefile. Thank you for the code changes and descriptions!
