### ISSUE TITLE
Unsupported for hipblas equivalent of Integer Datatypes.

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/hipBLAS#90]
The hipblas Datatypes equivalent is not supported for integer datatypes but supported in both  rocblas and cublas.
list of rocblas datatypes not supported in hipblas
        rocblas_datatype_i8_c
        rocblas_datatype_u8_r
        rocblas_datatype_u8_c
        rocblas_datatype_i32_r
        rocblas_datatype_i32_c
        rocblas_datatype_u32_r
        rocblas_datatype_u32_c

list of cublas Datatypes: 

        CUDA_R_8I = 3,   
        CUDA_C_8I = 7,   
        CUDA_R_8U = 8,   
        CUDA_C_8U = 9,   
        CUDA_R_32I= 10,  
        CUDA_C_32I= 11,  
        CUDA_R_32U= 12,  
        CUDA_C_32U= 13   

where as hipblas only supports  float datatypes as below
enum hipblasDatatype_t
{
    HIPBLAS_R_16F = 150,
    HIPBLAS_R_32F = 151,
    HIPBLAS_R_64F = 152,
    HIPBLAS_C_16F = 153,
    HIPBLAS_C_32F = 154,
    HIPBLAS_C_64F = 155,
};

**Comment by leekillough** [comment]
Fixed in #121
